# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/media/sf_Calculatrice/GUI/mainWindow.ui'
#
# Created: Mon May 23 15:21:12 2016
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(510, 527)
        self.verticalLayout_5 = QtGui.QVBoxLayout(Form)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.textEdit = QtGui.QTextEdit(Form)
        self.textEdit.setObjectName(_fromUtf8("textEdit"))
        self.verticalLayout_5.addWidget(self.textEdit)
        spacerItem = QtGui.QSpacerItem(20, 13, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_5.addItem(spacerItem)
        self.lineEdit = QtGui.QLineEdit(Form)
        font = QtGui.QFont()
        font.setPointSize(25)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.verticalLayout_5.addWidget(self.lineEdit)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.pushButton_6 = QtGui.QPushButton(Form)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setObjectName(_fromUtf8("pushButton_6"))
        self.horizontalLayout.addWidget(self.pushButton_6)
        self.pushButton_7 = QtGui.QPushButton(Form)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setObjectName(_fromUtf8("pushButton_7"))
        self.horizontalLayout.addWidget(self.pushButton_7)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.pushButton_16 = QtGui.QPushButton(Form)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_16.setFont(font)
        self.pushButton_16.setObjectName(_fromUtf8("pushButton_16"))
        self.horizontalLayout_2.addWidget(self.pushButton_16)
        self.pushButton_17 = QtGui.QPushButton(Form)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_17.setFont(font)
        self.pushButton_17.setObjectName(_fromUtf8("pushButton_17"))
        self.horizontalLayout_2.addWidget(self.pushButton_17)
        self.pushButton_18 = QtGui.QPushButton(Form)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_18.setFont(font)
        self.pushButton_18.setObjectName(_fromUtf8("pushButton_18"))
        self.horizontalLayout_2.addWidget(self.pushButton_18)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.pushButton_13 = QtGui.QPushButton(Form)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_13.setFont(font)
        self.pushButton_13.setObjectName(_fromUtf8("pushButton_13"))
        self.horizontalLayout_3.addWidget(self.pushButton_13)
        self.pushButton_14 = QtGui.QPushButton(Form)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_14.setFont(font)
        self.pushButton_14.setObjectName(_fromUtf8("pushButton_14"))
        self.horizontalLayout_3.addWidget(self.pushButton_14)
        self.pushButton_15 = QtGui.QPushButton(Form)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_15.setFont(font)
        self.pushButton_15.setObjectName(_fromUtf8("pushButton_15"))
        self.horizontalLayout_3.addWidget(self.pushButton_15)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.pushButton_10 = QtGui.QPushButton(Form)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_10.setFont(font)
        self.pushButton_10.setObjectName(_fromUtf8("pushButton_10"))
        self.horizontalLayout_4.addWidget(self.pushButton_10)
        self.pushButton_11 = QtGui.QPushButton(Form)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_11.setFont(font)
        self.pushButton_11.setObjectName(_fromUtf8("pushButton_11"))
        self.horizontalLayout_4.addWidget(self.pushButton_11)
        self.pushButton_12 = QtGui.QPushButton(Form)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_12.setFont(font)
        self.pushButton_12.setObjectName(_fromUtf8("pushButton_12"))
        self.horizontalLayout_4.addWidget(self.pushButton_12)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.pushButton_8 = QtGui.QPushButton(Form)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setObjectName(_fromUtf8("pushButton_8"))
        self.horizontalLayout_5.addWidget(self.pushButton_8)
        self.pushButton_9 = QtGui.QPushButton(Form)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_9.setFont(font)
        self.pushButton_9.setObjectName(_fromUtf8("pushButton_9"))
        self.horizontalLayout_5.addWidget(self.pushButton_9)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        spacerItem1 = QtGui.QSpacerItem(20, 25, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem1)
        self.horizontalLayout_6.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.pushButton_3 = QtGui.QPushButton(Form)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.verticalLayout.addWidget(self.pushButton_3)
        self.pushButton_2 = QtGui.QPushButton(Form)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.verticalLayout.addWidget(self.pushButton_2)
        self.pushButton_4 = QtGui.QPushButton(Form)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.verticalLayout.addWidget(self.pushButton_4)
        self.pushButton_5 = QtGui.QPushButton(Form)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setObjectName(_fromUtf8("pushButton_5"))
        self.verticalLayout.addWidget(self.pushButton_5)
        self.pushButton = QtGui.QPushButton(Form)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.verticalLayout.addWidget(self.pushButton)
        spacerItem2 = QtGui.QSpacerItem(20, 25, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem2)
        self.horizontalLayout_6.addLayout(self.verticalLayout)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.pushButton_19 = QtGui.QPushButton(Form)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_19.setFont(font)
        self.pushButton_19.setObjectName(_fromUtf8("pushButton_19"))
        self.verticalLayout_3.addWidget(self.pushButton_19)
        self.pushButton_20 = QtGui.QPushButton(Form)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_20.setFont(font)
        self.pushButton_20.setObjectName(_fromUtf8("pushButton_20"))
        self.verticalLayout_3.addWidget(self.pushButton_20)
        self.pushButton_21 = QtGui.QPushButton(Form)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_21.setFont(font)
        self.pushButton_21.setObjectName(_fromUtf8("pushButton_21"))
        self.verticalLayout_3.addWidget(self.pushButton_21)
        self.pushButton_22 = QtGui.QPushButton(Form)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_22.setFont(font)
        self.pushButton_22.setObjectName(_fromUtf8("pushButton_22"))
        self.verticalLayout_3.addWidget(self.pushButton_22)
        self.pushButton_23 = QtGui.QPushButton(Form)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_23.setFont(font)
        self.pushButton_23.setObjectName(_fromUtf8("pushButton_23"))
        self.verticalLayout_3.addWidget(self.pushButton_23)
        spacerItem3 = QtGui.QSpacerItem(20, 25, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_3.addItem(spacerItem3)
        self.horizontalLayout_6.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.pushButton_24 = QtGui.QPushButton(Form)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_24.setFont(font)
        self.pushButton_24.setObjectName(_fromUtf8("pushButton_24"))
        self.verticalLayout_4.addWidget(self.pushButton_24)
        self.pushButton_25 = QtGui.QPushButton(Form)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_25.setFont(font)
        self.pushButton_25.setObjectName(_fromUtf8("pushButton_25"))
        self.verticalLayout_4.addWidget(self.pushButton_25)
        self.pushButton_26 = QtGui.QPushButton(Form)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_26.setFont(font)
        self.pushButton_26.setObjectName(_fromUtf8("pushButton_26"))
        self.verticalLayout_4.addWidget(self.pushButton_26)
        self.pushButton_27 = QtGui.QPushButton(Form)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_27.setFont(font)
        self.pushButton_27.setObjectName(_fromUtf8("pushButton_27"))
        self.verticalLayout_4.addWidget(self.pushButton_27)
        self.pushButton_28 = QtGui.QPushButton(Form)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_28.setFont(font)
        self.pushButton_28.setObjectName(_fromUtf8("pushButton_28"))
        self.verticalLayout_4.addWidget(self.pushButton_28)
        spacerItem4 = QtGui.QSpacerItem(20, 25, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_4.addItem(spacerItem4)
        self.horizontalLayout_6.addLayout(self.verticalLayout_4)
        self.verticalLayout_5.addLayout(self.horizontalLayout_6)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Calculatrice by Bibosso", None))
        self.pushButton_6.setText(_translate("Form", "<-----", None))
        self.pushButton_7.setText(_translate("Form", "CE", None))
        self.pushButton_16.setText(_translate("Form", "7", None))
        self.pushButton_17.setText(_translate("Form", "8", None))
        self.pushButton_18.setText(_translate("Form", "9", None))
        self.pushButton_13.setText(_translate("Form", "4", None))
        self.pushButton_14.setText(_translate("Form", "5", None))
        self.pushButton_15.setText(_translate("Form", "6", None))
        self.pushButton_10.setText(_translate("Form", "1", None))
        self.pushButton_11.setText(_translate("Form", "2", None))
        self.pushButton_12.setText(_translate("Form", "3", None))
        self.pushButton_8.setText(_translate("Form", "0", None))
        self.pushButton_9.setText(_translate("Form", ",", None))
        self.pushButton_3.setText(_translate("Form", "+", None))
        self.pushButton_2.setText(_translate("Form", "-", None))
        self.pushButton_4.setText(_translate("Form", "/", None))
        self.pushButton_5.setText(_translate("Form", "*", None))
        self.pushButton.setText(_translate("Form", "=", None))
        self.pushButton_19.setText(_translate("Form", "cos", None))
        self.pushButton_20.setText(_translate("Form", "sin", None))
        self.pushButton_21.setText(_translate("Form", "tan", None))
        self.pushButton_22.setText(_translate("Form", "abs", None))
        self.pushButton_23.setText(_translate("Form", "sgn", None))
        self.pushButton_24.setText(_translate("Form", "acos", None))
        self.pushButton_25.setText(_translate("Form", "asin", None))
        self.pushButton_26.setText(_translate("Form", "atan", None))
        self.pushButton_27.setText(_translate("Form", "trunc", None))
        self.pushButton_28.setText(_translate("Form", "round", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    Form = QtGui.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

